fragment PageParts on Page {
  __typename
  title
  blocks {
    __typename
    ... on PageBlocksHero {
      headline
      subtext
      backgroundImage
      cta {
        __typename
        label
        url
      }
    }
    ... on PageBlocksMission {
      image
      imageSide
      content
    }
    ... on PageBlocksImpactGrid {
      stats {
        __typename
        value
        label
      }
    }
    ... on PageBlocksDonation {
      visible
      headline
      description
      methods {
        __typename
        label
        value
        helperText
      }
    }
    ... on PageBlocksEvents {
      label
      items {
        __typename
        title
        date
        location
      }
    }
    ... on PageBlocksContact {
      label
      address
      phone
      email
      mapEmbed
    }
    ... on PageBlocksImage {
      src
      alt
      fit
      position
      maxHeight
    }
    ... on PageBlocksFaq {
      label
      items {
        __typename
        question
        answer
      }
    }
    ... on PageBlocksTestimonials {
      label
      items {
        __typename
        quote
        author
        role
      }
    }
    ... on PageBlocksTimeline {
      label
      items {
        __typename
        date
        title
        description
      }
    }
  }
}

fragment GlobalParts on Global {
  __typename
  brandColor
  logo
  showPlaceholderLogo
  favicon
  organizationName
  slogan
  locale
  socialLabel
  navigation {
    __typename
    label
    url
  }
  social {
    __typename
    facebook
    instagram
  }
}
